services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capital-tracker
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file:
      - .env
